# Generated by Django 4.2.1 on 2023-05-12 13:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=20, unique=True, verbose_name='아이디')),
                ('email', models.EmailField(max_length=255, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=10, verbose_name='닉네임')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='프로필 사진')),
                ('age', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(20)], verbose_name='나이')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('fav_alcohol', models.CharField(blank=True, choices=[('SOJU', '소주'), ('BEER', '맥주'), ('WINE', '와인'), ('LIQUOR', '양주'), ('TAKJU', '탁주'), ('ETC', '기타'), ('NO', '응답하지 않음')], max_length=10, null=True, verbose_name='주종')),
                ('amo_alcohol', models.CharField(blank=True, choices=[('BABY', '알쓰'), ('CHOBO', '술찌'), ('JUNGSU', '애주가'), ('GOSU', '술꾼'), ('GOD', '디오니소스')], max_length=10, null=True, verbose_name='주량')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('followings', models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
